name: Build On Pull Request
on:
  pull_request:
    branches: [ "master","develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
          fetch-depth: 0 

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build with NPM and Maven
        run: |
          npm config set legacy-peer-deps true
          npm install -g @angular/cli
          npm install typescript@5.1.3 --save-dev
          npm install ng2-smart-table@1.2.1
          npm install node-sass
          npm install --force
          npm run build

