name: ESLint and NPM Audit

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.jsx'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.js
            **/*.ts
            **/*.tsx
            **/*.jsx

      - name: Run ESLint on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npx eslint ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run npm audit
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, 'package.json') || contains(steps.changed-files.outputs.all_changed_files, 'package-lock.json') }}
        run: npm audit
